config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	post '/join', to: 'attendees#create'
	delete '/leave/:id', to: 'attendees#destroy', as: :leave
	get '/my_events', to: 'users#my_events'
	resources :events
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user 
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true 
	belongs_to :creator, :class_name => "User"
	has_many :attendances
	has_many :users, through: :attendances
	has_many :invites


	default_scope -> { order(created_at: :desc) }

	scope :past, -> event_date { where("event_date < ?",Time.zone.now) }
	scope :upcoming, -> event_date { where("event_date > ?", Time.zone.now) }



end

app/models/invite.rb
class Invite < ApplicationRecord
	belongs_to :event 
	belongs_to :invitor, :class_name => "User"
	belongs_to :invitee, :class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_many :invitations, :foreign_key => "invitor_id", :class_name => "Invite"
	has_many :received_invites, :foreign_key => "invitee_id", :class_name => "Invite"
	has_many :attendances
	has_many :created_events, :foreign_key => "creator_id", :class_name => "Event", dependent: :destroy
	has_many :events, through: :attendances
  before_save :downcase_email 
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	#Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
												BCrypt::Engine.cost 
		BCrypt::Password.create(string, cost: cost)
	end

	#Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	#Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end 

	#forget a user
	def forget 
		update_attribute(:remember_digest, nil)
	end 

	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end   											  

  private
  def downcase_email
  	self.email = email.downcase 
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include SessionsHelper

	private
    #Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in or 1-900 Sign up linden."
      redirect_to login_url   
    end 
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

	def create
		@event = Event.find(params[:attendance][:event_id])
		@attend = current_user.attendances.create(event_id: @event.id)
		flash[:success] = "You Joined Successfully"
		redirect_back(fallback_location: events_path(@event))
	end 

	def destroy
		current_user.attendances.find_by(event_id: params[:id]).destroy
		flash[:success] = "You have Left the event"
		redirect_back(fallback_location: events_path(@event))
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in_user, only: [:new, :index]
	has_scope :past
	has_scope :upcoming

	def index
		@events = apply_scopes(Event).all
	end 

	def new
		@event = current_user.created_events.build
	end 

	def create
		@event = current_user.created_events.build(event_params)
		if @event.save
			flash[:success] = " oh shnap event created!"
			redirect_to events_path 
		else 
			render 'new'
		end 	
	end 

	def show
		@event = Event.find(params[:id])
		@attends = @event.attendances 
	end
 
	private

	def event_params
		params.require(:event).permit(:title, :body, :event_date)
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end 

	def create
		@user = User.find_by(email: params[:session][:email].downcase)
		if @user && @user.authenticate(params[:session][:password])
			log_in(@user)
			params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
			flash[:success] = "Oh shnap 1-900 linden logged in"
			redirect_to root_url
		else 
			flash.now[:danger] = "Oh shnap Invalid email/password combination"
			render 'new'
		end 	
	end

	def destroy
		log_out if logged_in?
		flash[:success] = "Oh Shnap you just logged out"
		redirect_to root_url 
	end  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end 
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	has_scope :past 
	has_scope :upcoming

	def new
		@user = User.new
	end 

	def create
		@user = User.new(user_params)
		if @user.save
			log_in(@user)
			flash[:success] = "Oh shnap you just signed up"
			redirect_to root_url
		else 
			render 'new'
		end 
	end

	def my_events
		@events = apply_scopes(current_user.events)
	end  

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def attending_event?
		attending = false 
		@attends.each do |attend|
			if attend.user == current_user
				attending = true 
			end
		end
		return attending 
	end 

end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Logs in the given user
	def log_in(user)
		session[:user_id] = user.id
	end 

	#Returns true if the given user is the current user
	def current_user?(user)
		user == current_user
	end 

	#returns true if the user is logged in, false otherwise
	def logged_in?
		!current_user.nil?
	end

	#Remembers a user in a persistent session.
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id 
		cookies.permanent[:remember_token] = user.remember_token
	end 
	
	#Returns the user corresponding to the remember token cookie.
	def current_user 
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
		if user && user.authenticated?(:remember, cookies[:remember_token])		 
			log_in(user)
			@current_user = user 
		end
		end  
	end

	#Forgets a persistent session
	def forget(user)
		user.forget 
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end  

	#logs out the current user
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil 
	end 
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<nav aria-label="...">
  <ul class="pager">
    <li class="previous"><%= link_to events_path(:past => true) do %> 
      <span aria-hidden="true">&larr;</span> 
      Past Events
      <% end %>
    </li>
        <li class="next"><%= link_to events_path(:upcoming => true) do %> 
      
      Upcoming Events
      <span aria-hidden="true">&rarr;</span> 
      <% end %>
    </li>
  </ul>
</nav>
    <h1> Events </h1>
    <% @events.each do |event| %>
<div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= event.title %></h4>
      </div>
      <div class="modal-body">
        <p><%= event.body %></p>
      </div>
      <div class="modal-footer">
        <%= link_to "Join Event", event_path(event), class: "btn btn-primary" %>
      </div>
    </a>
    </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>
<div class="row">
  <div class="f col-md-8">
<%= form_for(@event, url: events_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'b form-control' %>

  <%= f.label :event_description %>
  <%= f.text_area :body, class: 'form-control', size: "5x10" %>

  <%= f.label :Date_and_Time %>
   <div class='input-group date' id='datetimepicker1'>
    <%= f.text_field :event_date, class: 'form-control' %>
    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>

    </div>

  <%= f.submit "Create Event", class: "f btn btn-primary btn-lg btn-block" %>
<% end %> 
</div>

<div class="col-md-4">
	<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">To check out all of the events</h3>
  </div>
  <div class="panel-body">
    <%= link_to "Click Here", events_path, class: "btn btn-primary" %>
  </div>
</div>

</div>

</div>


 <script type="text/javascript">
    $(function () {
      $('#datetimepicker1').datetimepicker({

            format: 'DD/MM/YYYY HH:mm:ss'
          });
        });
 </script>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-8"><div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title"><%= @event.title %></h1>
      </div>
      <div class="modal-body">
        <p><%= @event.body %></p>
      </div>
      <% if attending_event? == false %>
      <div class="modal-footer">
        <%= form_for(current_user.attendances.build, url: join_path) do |f| %>
          <%= f.hidden_field :event_id, value: @event.id %>
          <%= f.submit "Attend", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
        <% else %>
        <div class="modal-footer">
        <%= form_for(current_user.attendances.find_by(event_id: @event.id), url: leave_path(@event), method: :delete)  do |f| %>
          <%= f.submit "Leave", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-info">
  <div class="panel-heading">
    <h2 class="panel-title">Attending</h2>
  </div>
  <div class="panel-body">

  <% @attends.each do |attend| %>
  <li><%= attend.user.name.capitalize %></li>
  <% end %>
  </div>
</div>
    
  </div>
</div>

app/views/layouts/_defaults.html.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#'  %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Private Events", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %>
          <i class="fa fa-home">Home</i>
          <% end %>
        </li>
        <li><%= link_to new_event_path do %>
          <i class="fa fa-indent">Events</i>
          <% end %>
        </li>
        
          <% if logged_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-cog"></i>My Settings <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "My Events", my_events_path %></li>
            <li class="divider"></li>
            <li><%= link_to "My Profile", '#' %></li>
          </ul>
        </li>
          <li>
            <%= link_to logout_path, method: :delete do %>
            <i class="fa fa-sign-out">Logout</i>
            <% end %>
          </li>
          <% else %>
          <li>
          <%= link_to signup_path do %>
          <i class="fa fa-circle-o-notch">Sign up</i>
          <% end %>
          </li>
          <li>
          <%= link_to login_path do %>
          <i class="fa fa-sign-in">Login</i>
          <% end %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= render 'layouts/defaults' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	
    <div class="container">
      <%= render 'shared/flash' %>
        
    
    <%= yield %>

		
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-danger">
  The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
   <li> <%= msg %> </li>
   <% end %>
   </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
      <% flash.each do |message_type, message| %>
      	<div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
     	  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      	<%= message %>  
      	<% end %>
      </div>

app/views/users/my_events.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<nav aria-label="...">
  <ul class="pager">
    <li class="previous"><%= link_to my_events_path(:past => true) do %> 
      <span aria-hidden="true">&larr;</span> 
      Past Events
      <% end %>
    </li>
        <li class="next"><%= link_to my_events_path(:upcoming => true) do %> 
      
      Upcoming Events
      <span aria-hidden="true">&rarr;</span> 
      <% end %>
    </li>
  </ul>
</nav>
    <h1> Created Events </h1>
    <% @events.each do |event| %>
<div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= event.title %></h4>
      </div>
      <div class="modal-body">
        <p><%= event.body %></p>
      </div>
      <div class="modal-footer">
       
      </div>
    </a>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class = "row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@user, url: signup_path, :html => {:class => 'form-horizontal'}) do |f| %>
  <fieldset>
    <%= render 'shared/error_messages', object: f.object %>
    <legend>Sign up</legend>

    <div class="form-group">

      <%= f.label :name, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
      <%= f.text_field :name, placeholder: "enter your name...", class: "form-control" %>
    </div>
    </div>

        <div class="form-group">
      <%= f.label :email, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
      <%= f.text_field :email, placeholder: "enter your email...", class: "form-control" %>
    </div>
    </div>

      <div class="form-group">
      <%= f.label :password, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
      <%= f.password_field :password, placeholder: "enter your password...", class: "form-control" %>
    </div>
    </div>
      
      <div class="form-group">
      <%= f.label :password_confirmation, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
      <%= f.password_field :password_confirmation, placeholder: "confirm your password...", class: "form-control" %>
    </div>
    </div>

        <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>

  </fieldset>
<% end %>
</div>
</div>
</div>